# lychee.toml
# Only scan built docs pages (adjust path if you use `out/` instead of `.next/`)
include = [
  ".next/server/app/docs/**/*.html"
]

# Exclude Next.js internals
exclude_path = [
  "**/_next/**",
  "**/*.js",
  "**/*.css",
  "**/*.json",
  "**/*.map",
]

# Ignore local file:// URIs (don’t make sense in CI)
# Domains you know require login / auth
exclude = [
  "file://*",
  "https://console.aquanode.ai/*",
]

# Handle rate-limited APIs (like Backblaze, GitHub, LinkedIn)
accept = ["200..299", "429"]

max_retries = 3
retry_wait_time = 2
timeout = 20